### ISSUE TITLE
Channels example client doesn't build with use-webrtc feature

### ISSUE THREAD

**Issue by johnpmayer** [smokku/bevy_networking_turbulence#11]
Trying to reconstruct the build commands for the channel example on web, but ran into issues.

Server works fine:

`env RUST_LOG=debug cargo run --example channels --no-default-features --features use-webrtc,bevy/default -- --server`

But client does not:

`cargo build --example channels --target wasm32-unknown-unknown --no-default-features --features use-webrtc,bevy/default`

Client fails to build - compile issue in wgpu - Lots of "unresolved import", "failed to resolve", and "cannot find type" in web_sys

Another crate feature missing?

**Comment by johnpmayer** [comment]
Bad luck, now the above command also fails with `libloading` and `slice-deque`

**Comment by johnpmayer** [comment]
It might be nice to refactor the examples to be a non-workspace sub-folders with a Cargo.lock once it's confirmed working.

**Comment by johnpmayer** [comment]
Working on this in #12

**Comment by smokku** [comment]
Added note about https://github.com/ostwilkens/arugio to README
