### ISSUE TITLE
How does this compare to using Laminar?

### ISSUE THREAD

**Issue by vegard-st1** [smokku/bevy_networking_turbulence#15]
I'm quite new to games networking so I have trouble comparing similar projects without some guidance.

How would this project compare to: [Bevy Networking with Laminar](https://github.com/ncallaway/bevy_prototype_networking_laminar)?

These are the features Laminar provides:
-  Fragmentation
-  Unreliable packets
-  Unreliable sequenced packets
-  Reliable unordered packets
-  Reliable ordered packets
-  Reliable sequenced packets
-  Rtt estimations
-  Protocol version monitoring
-  Basic connection management
-  Heartbeat
-  Basic DoS mitigation
-  High Timing control
-  Protocol Versioning
-  Well-tested by integration and unit tests
-  Can be used by multiple threads (Sender, Receiver)

I see that this project uses a stripped down version of WebRTC protocol, is there some of the features above which come for free because of that?

**Comment by smokku** [comment]
Bug Tracker is a place to raise issues and propose improvements to the code.
Please use a discussion platform like https://stackoverflow.com for free form discussion and asking questions.
