### ISSUE TITLE
Ability to manually close a connection

### ISSUE THREAD

**Issue by mvlabat** [smokku/bevy_networking_turbulence#17]
It would be great to add a possibility to forcibly close a connection with a peer.

While closing connections seems to be implied/covered by #6, this issue is intended to have a narrower scope.

Whereas #6 implies automatic connection tracking, this simple feature would allow working around the limitations of missing connection tracking by letting users take care of it on the application level.
Also, this feature will be useful even if automatic connection tracking arrives. For instance, forcible closing of a connection would mean emptying channel buffers, so that previous reliable messages wouldn't be resent.

Forcible closing of connection shouldn't imply that another peer can't send a message thus opening a connection again. I just expect the "closing" peer to stop trying to deliver old reliable messages.

I've never designed lower-level networking libraries, but I hope this feature request makes sense. Would be happy to hear what you think about it.

Thanks!

**Comment by RJ** [comment]
I think this one is also fixed with the recent changes.  You can use `NetworkResource::disconnect(handle)` yourself, or let the idle timeout feature clean up for you.

**Comment by mvlabat** [comment]
@RJ thank you a lot for implementing it! I haven't tested it in my project yet, but I'm ok if this issue will be closed.

Looking forward to upgrading to 0.3 now! :)

**Comment by smokku** [comment]
TY
