### ISSUE TITLE
Bevy 0.5 support

### ISSUE THREAD

**Issue by nikitavondel** [smokku/bevy_networking_turbulence#19]
The plugin no longer works with the latest Bevy release.
Is this awesome networking plugin going to support 0.5 in the near future?

**Comment by smokku** [comment]
Being worked on in #18

**Comment by phuoc-thanh** [comment]
You can checkout #18 , it works with bevy 0.5 except examples. I will take time to update examples, hopefully this weekend.

**Comment by nikitavondel** [comment]
I can also confirm this networking plugin works with the aforementioned fork/updates when leaving out the examples. Thank you very much, guys! This issue can be closed if you ask me.

**Comment by smokku** [comment]
Fixed by #23
