### ISSUE TITLE
(Win10) Wasm server crashes on startup

### ISSUE THREAD

**Issue by ostwilkens** [smokku/bevy_networking_turbulence#2]
First, small fix for readme: 
`cargo run --example simple --no-default-features --features use-webrtc -- --server`
(missing `--no-default-features`)

This is the error: 
```
PS C:\Projects-temp\bevy_networking_turbulence> cargo run --example simple --no-default-features --features use-webrtc -- --server
Finished dev [unoptimized + debuginfo] target(s) in 0.26s
Running `target\debug\examples\simple.exe --server`
error: process didn't exit successfully: `target\debug\examples\simple.exe --server` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
```

`STATUS_DLL_NOT_FOUND`
Most definitely a windows-specific error! 
It is triggered when calling `net.listen`. I will dig and see if I can trace it further.

**Comment by ostwilkens** [comment]
I traced this down to the openssl crate. It's a bit finicky on windows. 
In my case I needed to add `C:\Projects\vcpkg\packages\openssl_x64-windows\bin` to path. 

Related reading: 
https://github.com/sfackler/rust-openssl/issues/1062

**Comment by smokku** [comment]
`--no-default-features` is already fixed on master.

And yeah - OpenSSL is PITA on Windows. I don't even remember how I did configure it.

IIRC I downloaded the windows build and had to set:
```
OPENSSL_DIR=C:\Program Files\OpenSSL-Win64\bin
OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL-Win64\include
OPENSSL_LIB_DIR=C:\Program Files\OpenSSL-Win64\lib
```
