### ISSUE TITLE
naia-socket 0.6

### ISSUE THREAD

**Issue by billyb2** [smokku/bevy_networking_turbulence#21]
What do you think of upgrading to the latest version of naia-client-socket and naia-server-socket? Currently, there's a bug with naia-client-socket that doesn't allow it to work in Firefox without either manual patching or using the latest version.

**Comment by smokku** [comment]
On a quick look 0.6 upgrade is an API breaking change.

Unfortunately, I do not have enough free time now to work on making necessary code changes to update the plugin.

**Comment by billyb2** [comment]
> On a quick look 0.6 upgrade is an API breaking change.
> 
> Unfortunately, I do not have enough free time now to work on making necessary code changes to update the plugin.

Yea it is a breaking change, though I made a PR to the Bevy 0.5 PR that implements it, not very much changed.

**Comment by phuoc-thanh** [comment]
Nice, will take a look on that.

**Comment by billyb2** [comment]
> Nice, will take a look on that.

Thank you, please let me know what you think.

**Comment by smokku** [comment]
Closed by #24
