### ISSUE TITLE
Call flush once per tick rather than after every send_message

### ISSUE THREAD

**Issue by RJ** [smokku/bevy_networking_turbulence#27]
Currently turbulence's channel `flush()` is called within each call to `NetworkResource::send_message` or `broadcast_message`. This will immediately send a packet containing the message.

If I understand correctly, one of the features of turbulence messages is that, given they must be less than the size of a packet, it coalesces them such that multiple messages are sent per packet.

By flushing each send, we are only ever sending 1 message per packet.

In the case of bevy, surely it would be better to `flush()` each channel once at the end of a tick, so that all the small messages that were sent by systems during that tick can be coalesced into fewer packets.

Perhaps exposing a flush_all_messages.system() that the user can run in an appropriate stage?

Thanks for a great library btw :)

**Comment by RJ** [comment]
Relevant unmerged PR where flushing strategy is mentioned: https://github.com/kyren/turbulence/pull/4/files

**Comment by smokku** [comment]
My reasoning is that you usually want to hit the network as soon as it it possible, to minimize latency.
But I do understand that you may want to manually control flushing when you know that you want fit more into one packet.

Agreed. An option to disable autoflushing + a system sounds like a good idea.

**Comment by SamiPirbay** [comment]
Is there a way to set the flushing strategy per channel?

In my use case, I send state updates once per tick, but I send user input right away to minimize latency.

Having a setting in `MessageChannelSettings` seems natural/convenient, but I just realized it's in the `turbulence` crate.

**Comment by smokku** [comment]
You can have a system that flushes messages whenever you want.
See example: https://github.com/smokku/bevy_networking_turbulence/blob/master/examples/message_coalescing.readme.md#manually-flushing-channels-after-each-tick
