### ISSUE TITLE
Branch to keep up-to-date with bevy repo?

### ISSUE THREAD

**Issue by Stumblinbear** [smokku/bevy_networking_turbulence#41]
The Bevy `main` repo has upgraded `wasm-bindgen`, and renamed the `AppBuilder` to just `App`. Is there a possibility of keeping a branch up-to-date with bevy repo until an official release is made? I've worked around this by pulling the repo and making the changes locally, but it would be preferable to use the git repo.

An additional branch would mean fixes can be applied to the main branch (for the "official" bevy release) without breaking any existing dependencies.

**Comment by smokku** [comment]
There is a possibility. PRs welcome.

**Comment by smokku** [comment]
Fixed by #42
