### ISSUE TITLE
Use LogPlugin instead of simple_logger in examples

### ISSUE THREAD

**Issue by itytophile** [smokku/bevy_networking_turbulence#43]
Hi. I can't run the `simple` example on Arch Linux because of a panic from simple_logger:
```
thread 'main' panicked at 'Could not determine the UTC offset on this system. Possible causes are that the time crate does not implement "local_offset_at" on your system, or that you are running in a multi-threaded environment and the time crate is returning "None" from "local_offset_at" to avoid unsafe behaviour.
```
The cause of this panic is not important, we can replace simple_logger with the `LogPlugin` from Bevy and the example works like a charm (on wasm too):

```rs
.add_plugin(LogPlugin)
```

If you agree, I can make a pull request to fix the examples.

**Comment by smokku** [comment]
Sure - go ahead. :-)
