### ISSUE TITLE
Client / Server running inside same instance

### ISSUE THREAD

**Issue by robinlacey** [smokku/bevy_networking_turbulence#5]
Hello,

Firstly, thank you for making this library - it's been great fun to play around with.

For development speed I'd like to have the Server and Client logic running inside the same Bevy instance. Similar to your balls example, the client would events send through the reliable channel at 60fps and the server would broadcast state via an unreliable channel on state update. 

It'd be good to be able to separate the client side logic and the server side simulation as soon as possible as the porotype will be p2p.

Having the NetworkResource listen() and connect() on the same address  / port has been predictably problematic with broadcast messages not being received. Can you think of any quick work-arounds?

**Comment by smokku** [comment]
How are you going to separate server and client entities in a shared Bevy ECS world?

**Comment by robinlacey** [comment]
Good point! I'm just using the Client ECS to tick a pure simulator function (Simulator(State)->State). As no data models are sent over the bounds the components aren't coupled and can be split into services later. This approach probably isn't right for this use case though.

For a single start Client / Server - perhaps it'd be easier to have `bevy-client` in one crate and `bevy-server` in another then then thread::spawn both Bevy Apps - rather than different repos and a docker-compose? 

I'm guessing there may still be some threading issues ?

**Comment by smokku** [comment]
Bevy does not support running in a sub-thread. There are systems that require running on main-thread.
