### ISSUE TITLE
Missing connection tracking

### ISSUE THREAD

**Issue by smokku** [smokku/bevy_networking_turbulence#6]
> if you quit a client application and then open a new one on the same port it can't reconnect to the server again until you restart the server :grimacing:

**Comment by smokku** [comment]
Just tried reproducing on Linux + UDP using the `simple` example and the server didn't even notice the disconnection.

![image](https://user-images.githubusercontent.com/147687/103764021-04cfd300-501b-11eb-8ecd-e93145798681.png)

Needs further investigation.

**Comment by smokku** [comment]
The issue should be reproducible using channels.

**Comment by JCapucho** [comment]
I tried implementing this but it's kinda hard with the current api because if we don't use channels everything goes trough `receive_packets` so it's easy to keep the time since the connection last received a message but with channels the user is the one to poll and there's no way to update state with when the last message was received

**Comment by JCapucho** [comment]
Also when not using channels there's no way for us to automatically handle disconnects (i.e. On drop or trough a `disconnect` method) since with channels we can send trough a specific channel (with a dummy struct) but with no channels there's no way to add information to the packet without possibly conflicting with user data

**Comment by johnpmayer** [comment]
"no channels" seems like it could be removed from the API; presumably one could just use a single unreliable channel. would that be a considerable amount of overhead compared to no channels?

**Comment by smokku** [comment]
I want to keep the option of not using `turbulence` layer and building own protocol on top of raw packets.

**Comment by johnpmayer** [comment]
So I took some time to play around with naia-socket directly, and I've read through the repository to understand a bit of what's going on, the way the plugins, systems, and background "tasks" fit together.

I feel like a good user-facing API could be achieved by splitting into two plugins, which could share a decent amount the runtime "core" but just have different interfaces.

The lower-level plugin would just give you the single unreliable non-channel interface. It would be entirely up to the user to implement connection tracking.

The higher-level plugin would (and perhaps this could be an optional feature) register an internal connection-tracking channel (using an internal message type), as well as adds the bevy system which does the tracking.

This neatly works around the issue of user message conflicts with tracking messages. I'm not worried about the downside that connection tracking wouldn't be available in the low-level non-channels plugin; users of the low-level plugin would probably understand and be OK with rolling their own tracking (if that is even desired).

Thoughts?

**Comment by smokku** [comment]
I like the idea of two plugins - high-level plugin (wrapping features of channels example) building on features provided by low-level plugin (current one).

**Comment by smokku** [comment]
@RJ can this issue be closed, as we do have connection tracking now?

**Comment by RJ** [comment]
> @RJ can this issue be closed, as we do have connection tracking now?

I would say so, yes. You can restart client without restarting server now. And with idle timeouts the server cleans up automatically. 

We also now have `NetworkResource::disconnect(handle)` for when you need to manually drop a connection.
