### ISSUE TITLE
Wasm-bindgen gets compiled even for non-wasm32 targets

### ISSUE THREAD

**Issue by mvlabat** [smokku/bevy_networking_turbulence#8]
I haven't figured out which dependency that is exactly, but something is leaking `wasm-bindgen`

**Comment by smokku** [comment]
`cargo tree` should show it.

**Comment by mvlabat** [comment]
Oh, cool, I didn't know takes current target into account.

As far as I understand, this makes it compile `futures-timer` with `wasm-bindgen` feature enabled:

```
[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-timer = { version = "3.0", features = ["wasm-bindgen"] }
```

See https://github.com/rust-lang/cargo/issues/1197

The new feature resolver was stabilized recently, I actually believe it'll be possible to fix this with the next Rust release! Meanwhile, this could be worked-around with introducing `wasm-bindgen` feature to `bevy_networking_turbulence`, just like they do in every other crate.

**Comment by smokku** [comment]
I just checked `cargo tree` and `wasm-bindgen` is under `dev-dependencies` and not under `dependencies`. So IIUC this issue is solved.

```
[dev-dependencies]
├── bevy v0.4.0
│   └── bevy_internal v0.4.0
│ [...]
├── console_error_panic_hook v0.1.6
│   ├── cfg-if v0.1.10
│   └── wasm-bindgen v0.2.71
│       ├── cfg-if v1.0.0
│ [...]
```

**Comment by mvlabat** [comment]
Well, I'd like to avoid compiling `wasm-bindgen` even in the dev environment if possible. If I'm interested only in the UDP stack, for example, I'd like to avoid affecting my clean build time by WASM tools. It's even more noticeable in CI.

**Comment by smokku** [comment]
If you are not developing `bevy_networking_turbulence` itself, you are not compiling `dev-dependencies`. It is used only to build examples project.

If you have the library in your `dependencies` you are compiling library `dependencies` only, not `dev-dependencies`.

**Comment by mvlabat** [comment]
Oh, you're right. I also remember that `wasm-bindgen` was coming from `futures-timer`, but you've feature-gated it, so it's really good now. Thanks!
